# Generated by Django 4.1 on 2023-07-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apptodo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1999-1-3"),
            preserve_default=False,
        ),
    ]
